version: "3"

services:
  dev-environment:
    image: mnist-demo-pipeline-dev
    volumes:
    - ./workspace:/home/host_user/workspace
    ports:
    - "8888:8888"
    command:
    - |
      cd /home/host_user/workspace/

      # install "common" Python package in editable mode
      (cd common; make install clean)

      jupyter notebook --no-browser --port 8888 --ip 0.0.0.0
    hostname: mnist-demo-pipeline-dev
