version: "3.6"

services:
  dev-environment:
    image: mnist-demo-pipeline-local-dev
    volumes:
    - ../workspace:/home/host_user/workspace
    - ../pipeline-outputs:/pipeline-outputs
    ports:
    - "8888:8888"
    environment:
      RUN_ENVIRONMENT: "dev"
    command:
    - |
      cd /home/host_user/workspace/

      # install "common" Python package in editable mode
      (cd common; make install-editable clean)

      jupyter notebook --no-browser --port 8888 --ip 0.0.0.0
    hostname: mnist-demo-pipeline-local-dev
