name: "Reusable workflow to update static website"

# References on reusable workflows:
# - https://docs.github.com/en/actions/using-workflows/reusing-workflows
# - https://github.community/t/cant-call-reusable-workflow-unexpected-value-uses/204182

on:
  workflow_call:

jobs:
  update-static-website:
    name: Build and deploy static website
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: pynb-dag-runner/pynb-dag-runner
          path: pynb-dag-runner-repo
          persist-credentials: true

      - name: "Build Docker file"
        working-directory: ${{ github.workspace }}/pynb-dag-runner-repo/otel_output_parser
        shell: bash
        run: |
          make docker-build

      - name: "Fetch all artefacts into directory tree"
        working-directory: ${{ github.workspace }}/pynb-dag-runner-repo/otel_output_parser
        shell: bash
        run: |
          # GITHUB_REPOSITORY has format owner/repo-name.
          make docker-run-command \
              DOCKER_RUN_ARGS="\
                  --volume ${{ github.workspace }}:/github_workspace \
                  -e GITHUB_TOKEN \
                  -e GITHUB_REPOSITORY \
              " \
              COMMAND="\
                  pip install -e .; \
                  static_builder \
                      --github_repository $GITHUB_REPOSITORY \
                      --output_dir /github_workspace/www-root/pipeline-artifacts/ \
                      --output_static_data_json /github_workspace/www-root/ui_static_data.json; \
              "
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Store ui_static_data.json with data for UI (for easier offline debugging)"
        uses: actions/upload-artifact@v2
        with:
          name: ui-static-data
          path: |
              ${{ github.workspace }}/www-root/ui_static_data.json
          if-no-files-found: error
          retention-days: 5

      ###
      ### Fetch UI assets
      ###
      - name: "pip install package with assets for static web front end"
        working-directory: ${{ github.workspace }}/pynb-dag-runner-repo/otel_output_parser
        # ^-- this directory is where makefile is located
        shell: bash
        run: |
          echo "---"
          pwd
          echo "---"
          ls -la .
          echo "---"
          cat makefile
          echo "---"
          make docker-run-command \
              DOCKER_RUN_ARGS="\
                  --volume ${{ github.workspace }}:/github_workspace \
              " \
              COMMAND="\
                  cd /github_workspace; \
                  pip install pynb_dag_runner_webui \
                      --target pynb_dag_runner_webui; \
                  cp -r \
                      /github_workspace/pynb_dag_runner_webui/assets/. \
                      /github_workspace/www-root/; \
              "

      ###
      ### Deploy UI + data
      ###
      - name: "Push www-root content to repo gh-pages branch"
        working-directory: ${{ github.workspace }}/www-root
        shell: bash
        run: |
          # Github pages does not allow directory listing, add files in root
          # for troubleshooting
          find . > list_all_files.txt
          du -hs * > disk_usage.txt

          git init
          git checkout -b gh-pages

          git add -A

          git config --local user.email "gh-automation-bot@github.com"
          git config --local user.name "GitHub Action Bot"
          git commit -m "update"

          git push --force \
            https://my_token_user:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git \
            gh-pages:gh-pages
