name: "Reusable workflow to update static website"

# References on reusable workflows:
# - https://docs.github.com/en/actions/using-workflows/reusing-workflows
# - https://github.community/t/cant-call-reusable-workflow-unexpected-value-uses/204182

on:
  workflow_call:

jobs:
  update-static-website:
    name: Build and deploy static website
    runs-on: ubuntu-20.04
    steps:
      # v ------- This block fetches all logs and builds assets for static UI ---------v

      # This should be simplified: refactored into a separate gha, or makefile task?
      #
      # Note that the below depends on packages (see the pip install commands)
      #
      #   - pynb-dag-runner
      #   - pynb_dag_runner_webui
      #
      # These would better be somehow installed in a docker container (to collect all
      # dependencies into one place).

      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: "Build Docker file"
        working-directory: ${{ github.workspace }}
        shell: bash
        run: |
          (cd docker; make build-base-env-docker-image)

      - name: "Fetch all artefacts into directory tree"
        working-directory: ${{ github.workspace }}
        shell: bash
        run: |
          # GITHUB_REPOSITORY has format owner/repo-name.
          make run[in-base-docker] \
              EXTRA_FLAGS="\
                  --volume ${{ github.workspace }}:/github_workspace \
                  -e GITHUB_TOKEN \
                  -e GITHUB_REPOSITORY \
              " \
              COMMAND="\
                  pip install pynb-dag-runner-snapshot==0.0.8.dev1665829343; \
                  static_builder \
                      --github_repository $GITHUB_REPOSITORY \
                      --output_dir /github_workspace/www-root/pipeline-artifacts/ \
                      --output_static_data_json /github_workspace/www-root/ui_static_data.json; \
              "
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "pip install package with static assets for web front end"
        working-directory: ${{ github.workspace }}
        shell: bash
        run: |
          make run[in-base-docker] \
              EXTRA_FLAGS="\
                  --volume ${{ github.workspace }}:/github_workspace \
              " \
              COMMAND="\
                  pip install pynb_dag_runner_webui \
                      --target /github_workspace/pynb_dag_runner_webui; \
                  cp -r \
                      /github_workspace/pynb_dag_runner_webui/assets/. \
                      /github_workspace/www-root/; \
              "

      # ^ ------- This block fetches all logs and builds assets for static UI ---------^

      - name: "debug: Store ui_static_data.json with data for UI"
        uses: actions/upload-artifact@v2
        with:
          name: ui-static-data
          path: |
              ${{ github.workspace }}/www-root/ui_static_data.json
          if-no-files-found: error
          retention-days: 5

      ###
      ### Deploy UI + data
      ###
      - name: "Push www-root content to repo gh-pages branch"
        working-directory: ${{ github.workspace }}/www-root
        shell: bash
        run: |
          # Github Pages does not allow directory listing.
          # Add files for troubleshooting in the browser.
          find . > list_all_files.txt
          du -hs * > disk_usage.txt

          git init
          git checkout -b gh-pages

          git add -A

          git config --local user.email "gh-automation-bot@github.com"
          git config --local user.name "GitHub Action Bot"
          git commit -m "update"

          git push --force \
            https://my_token_user:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git \
            gh-pages:gh-pages
