name: "Run automated tests and the mnist-digit-demo-pipeline"

on:
  push:
    branches:
      - development

  # See:
  # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - development

  workflow_dispatch:

# GITHUB_TOKEN: add read access to repo (which is already public), but no other permissions
permissions:
  contents: read

jobs:
  run-all-tests:
    runs-on: [ubuntu-20.04]

    steps:
      - name: "Determine run-environment"
        shell: bash
        run: |
          echo "RUN_ENVIRONMENT=ci" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: false

      - name: "Build docker image"
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          make docker-build-all

      - name: "common: Run unit tests"
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          make \
              COMMAND="(cd commmon; make test-pytest )" \
              docker-run-in-cicd

      - name: "common: Run mypy type checks"
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          make \
              COMMAND="(cd commmon; make test-mypy )" \
              docker-run-in-cicd

      - name: "common: Check black formatting"
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          make \
              COMMAND="(cd commmon; make test-black )" \
              docker-run-in-cicd

      #- name: "Store wheel-file as build artefact"
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: pynb_dag_runner
      #    path: ${{ github.workspace }}/workspace/pynb_dag_runner/dist/
      #    if-no-files-found: error
      #    retention-days: 10
