name: "Run automated tests and the mnist-digit-demo-pipeline"

on:
  push:
    branches:
      - development

  # See:
  # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - development

  workflow_dispatch:

# Give GITHUB_TOKEN minimal permissions (ie., only metadata read-access). To
# verify this, check the "Set up jobs" section in the Github actions log.
#
# See:
# https://docs.github.com/en/actions/reference/authentication-in-a-workflow
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions
#
# and also links in:
# https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/
permissions:
  metadata: "none"

jobs:
  run-all-tests:
    runs-on: [ubuntu-20.04]

    steps:
      - name: "Determine run-environment"
        shell: bash
        run: |
          echo "RUN_ENVIRONMENT=ci" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: false

      - name: "Build docker image"
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          make docker-build-all

      - name: "common: Run unit tests"
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          make \
              COMMAND="(cd commmon; make test-pytest )" \
              docker-run-in-cicd

      - name: "common: Run mypy type checks"
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          make \
              COMMAND="(cd commmon; make test-mypy )" \
              docker-run-in-cicd

      - name: "common: Check black formatting"
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          make \
              COMMAND="(cd commmon; make test-black )" \
              docker-run-in-cicd

      #- name: "Store wheel-file as build artefact"
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: pynb_dag_runner
      #    path: ${{ github.workspace }}/workspace/pynb_dag_runner/dist/
      #    if-no-files-found: error
      #    retention-days: 10
