name: "Update static website"

on:
  push:
    branches:
      - development

  pull_request:
    branches:
      - development

  workflow_dispatch:

permissions:
  contents: "none"  # project repo:s are public

jobs:
  run-all-tests:
    runs-on: [ubuntu-20.04]

    steps:
      - name: "Clone pynb-dag-runner ci-utils repo"
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
            git clone git@github.com:pynb-dag-runner/ci-utils.git
            cd ci-utils
