name: "Update static website"

on:
  push:
    branches:
      - development

  pull_request:
    branches:
      - development

  workflow_dispatch:

permissions:
  contents: "read"

defaults:
  run:
    shell: bash
    working-directory: ${{ github.workspace }}

jobs:
  run-all-tests:
    runs-on: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3
        with:
          repository: pynb-dag-runner/ci-utils
          persist-credentials: true

      - name: "Install Taskfile"
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b .
          ./task --version
          ./task --list

      - name: "Build Docker file"
        run: |
          ./task docker:build
