name: "Update static website"

on:
  push:
    branches:
      - development

  pull_request:
    branches:
      - development

  workflow_dispatch:

permissions:
  contents: write

defaults:
  run:
    shell: bash
    # working-directory: ${{ github.workspace }}

jobs:
  update-static-website:
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: pynb-dag-runner/ci-utils
          persist-credentials: true
          path: ci-utils

      - name: "Install Taskfile"
        working-directory: ${{ github.workspace }}
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b .
          ./task --version

      - name: "Build Docker file"
        working-directory: ${{ github.workspace }}
        run: |
          cd ci-utils
          ../task docker:build

      - name: "Fetch all artefacts into directory tree"
        working-directory: ${{ github.workspace }}
        run: |
          docker run -t --rm \
            --volume $GITHUB_WORKSPACE:/github_workspace \
            -e GITHUB_TOKEN \
            ci-tools-image "(\
              cd /github_workspace/ci-utils/workspace; \
              pip install -e .; \
              static_builder \
                --gh_repo_owner pynb-dag-runner \
                --gh_repo_name mnist-digits-demo-pipeline \
                --output_dir /github_workspace/wwwroot/pipeline-artefacts/; \
            )"
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          GITHUB_WORKSPACE: ${{ github.workspace }}

      - name: "Push wwwroot content to repo gh-pages branch"
        working-directory: ${{ github.workspace }}
        run: |
          cd ${{ github.workspace }}/wwwroot

          find . > all_files.txt
          du -hs * > usage.txt

          git init
          git checkout -b gh-pages

          git add -A

          git config --local user.email "gh-automation-bot@github.com"
          git config --local user.name "GitHub Action Bot"
          git commit -m "update"

          git push --force \
            https://my_token_user:${{ secrets.github_token }}@github.com/pynb-dag-runner/mnist-digits-demo-pipeline.git \
            gh-pages:gh-pages
