name: "Update static website"

on:
  push:
    branches:
      - development

  pull_request:
    branches:
      - development

  workflow_dispatch:

permissions:
  contents: "none"  # project repo:s are public

jobs:
  run-all-tests:
    runs-on: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3
        with:
          name:  pynb-dag-runner/ci-utils
          persist-credentials: true

      - name: "test content"
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
            ls -la .
            cd ci-utils
            ls -la .
