name: "Update static website"

on:
  push:
    branches:
      - development

  pull_request:
    branches:
      - development

  workflow_dispatch:

permissions:
  contents: "read"

jobs:
  run-all-tests:
    runs-on: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3
        with:
          repository: pynb-dag-runner/ci-utils
          persist-credentials: true

      - name: "test content"
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
            ls -la .
            echo $PATH
            wget -h
            curl -h
            sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin
