name: "Manually update static website"

on:
  workflow_dispatch:

jobs:
  build-and-deploy-static-mlflow-site:
    permissions:
      contents: write # grant write access to update repo's static website
    uses: pynb-dag-runner/gha-build-and-publish-static-webui/.github/workflows/deploy-to-github-page.yml@initial-setup
    secrets:
      CALLER_ACTION_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
