name: "Manually update static website"

on:
  workflow_dispatch:

jobs:
  build-and-deploy-static-mlflow-site:
    uses: composable-logs/gha-build-and-publish-static-webui/.github/workflows/deploy-to-github-page.yml@main
    with:
      composable-logs-package: composable-logs-snapshot

    # Grant GITHUB_TOKEN write access to this repo (to allow updates to
    # gh-pages branch, and inject token.
    permissions:
      contents: write
    secrets:
      CALLER_ACTION_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
